#!/bin/bash
### BEGIN INIT INFO
# Provides:          raspberry_pi_camera
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: forever running /home/pi/Documents/raspberry_akitabox_camera/app.js
# Description:       /home/pi/Documents/raspberry_akitabox_camera/app.js
### END INIT INFO
#
# initd a node app
# Based on a script posted by https://gist.github.com/jinze at https://gist.github.com/3748766
#
# sudo cp /home/pi/Documents/raspberry_akitabox_camera/raspberry_pi_camera /etc/init.d/raspberry_pi_camera
# sudo update-rc.d raspberry_pi_camera defaults

# Source function library.
. /lib/lsb/init-functions

pidFile="/var/run/raspberry_pi_camera.pid"
logFile="/home/pi/Documents/raspberry_akitabox_camera/logs/camera.log"

command="/home/pi/node/node-v0.10.28-linux-arm-pi/bin/node"
nodeApp="/home/pi/Documents/raspberry_akitabox_camera/app.js"
foreverApp="/home/pi/node/node-v0.10.28-linux-arm-pi/bin/forever"

start() {
   echo "Starting $nodeApp"

   # Notice that we change the PATH because on reboot
   # the PATH does not include the path to node.
   # Launching forever with a full path
   # does not work unless we set the PATH.
   
   PATH=/home/pi/node/node-v0.10.28-linux-arm-pi/bin:/usr/local/bin:$PATH
   export NODE_ENV=production
   export RPI_CONFIG=/home/pi/Documents/raspberry_akitabox_camera/lib/config_files/config.js

   #PORT=80
   
   $foreverApp start --pidFile $pidFile -l $logFile -a -d -c "$command" $nodeApp
   RETVAL=$?
}

restart() {
   echo -n "Restarting $nodeApp"
   $foreverApp restart $nodeApp
   RETVAL=$?
}

stop() {
   echo -n "Shutting down $nodeApp"
   $foreverApp stop $nodeApp
   RETVAL=$?
}

status() {
   echo -n "Status $nodeApp"
   $foreverApp list
   RETVAL=$?
}

case "$1" in
   start)
        start
        ;;
    stop)
        stop
        ;;
   status)
        status
       ;;
   restart)
   	restart
        ;;
	*)
       echo "Usage:  {start|stop|status|restart}"
       exit 1
        ;;
esac
exit $RETVAL
